#!/bin/bash
#PBS -l nodes=1:ppn=8:dc2,walltime=0:05:00
#PBS -N biasfielcorr
#PBS -V

cd $PBS_O_WORKDIR
module load ants

rm -f t1.nii.gz
rm -f finished

N4BiasFieldCorrection -d 3 -i $(jq -r .t1 config.json) -o t1.nii.gz -s 4 -b [200] -c [50x50x50x50, 0.000001]


if [ -s t1.nii.gz ]
then 
     echo 0 > finished
else
	echo "Bias Correction Failed"
	echo 1 > finished
	exit 1
fi