#!/bin/bash
#PBS -l nodes=1:ppn=8:dc2,vmem=16gb,walltime=0:15:00
#PBS -N biasfielcorr
#PBS -V

module load ants
rm -f dwi.nii.gz

cp $(jq -r .bvals config.json) ./dwi.bvals
cp $(jq -r .bvecs config.json) ./dwi.bvecs


N4BiasFieldCorrection -d 3 -i $(jq -r .dwi config.json) -o [dwi.nii.gz, bias.nii.gz] -s 4 -b [600] -c [50x50x50x50, 0.000001]


